### ISSUE TITLE
Login link email not sent

### ISSUE THREAD

**Issue by allentiak** [clojure-camp/myclojurecamp#22]
Hi,
I am trying to login to my account, with no avail.

* I go to https://my.clojure.camp
* I input my email.
* press "Login"
* The website says it has sent the login link to my email.
* I don't receive the email.
* I have already checked my spam folder, but I have not received any emails from Clojure Camp today.

**Comment by rafd** [comment]
Can you try again now? There was a db issue the other day. I justed test the emailing and it worked for me.

**Comment by allentiak** [comment]
I've just tested it, and it works now.
Thanks for your hard work, @rafd !
